import { Exercise } from '@/types'

export const EXERCISES: Exercise[] = [
  // ─── CHEST ────────────────────────────────────────────────────────────────
  {
    id: 'push_up',
    name: 'Отжимания',
    name_en: 'Push-up',
    category: 'chest',
    movement_pattern: 'push_horizontal',
    modality: 'strength',
    primary_muscles: ['chest'],
    secondary_muscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    location: ['home', 'gym', 'outdoor'],
    difficulty: 1,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [10, 20],
    default_rest_sec: 60,
    tempo: '2-0-1-0',
    breathing: 'Вдох вниз, выдох на подъёме',
    contraindications: ['wrist'],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Провисание таза',
        consequence: 'Нагрузка на поясницу',
        correction: 'Держи тело прямым как доска — напряги ягодицы и кор',
      },
      {
        description: 'Локти слишком широко',
        consequence: 'Стресс на плечевые суставы',
        correction: 'Локти под углом 45° от корпуса, не 90°',
      },
    ],
    setup_steps: [
      'Встань в планку, ладони чуть шире плеч',
      'Пальцы направлены вперёд или слегка наружу',
      'Тело прямое от головы до пяток',
    ],
    execution_steps: [
      'Медленно опускайся, пока грудь почти не коснётся пола',
      'Держи локти под углом 45°',
      'Оттолкнись вверх, полностью выпрямляя руки',
    ],
    key_cues: ['Тело — доска', 'Локти 45°', 'Выдох на усилии'],
    safety_tips: ['Остановись при боли в запястьях', 'Начинай с колен если нужно'],
    easier_variations: ['push_up_knees', 'wall_push_up'],
    harder_variations: ['push_up_diamond', 'push_up_archer', 'push_up_clap'],
    alternatives: ['dumbbell_bench_press', 'chest_press_machine'],
    tags: ['compound', 'bodyweight', 'chest', 'beginner'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    name_en: 'Goblet Squat',
    category: 'legs',
    movement_pattern: 'squat',
    modality: 'strength',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['dumbbell', 'kettlebell'],
    location: ['home', 'gym'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [10, 15],
    default_rest_sec: 60,
    tempo: '2-1-2-0',
    breathing: 'Вдох вниз, выдох при вставании',
    contraindications: [],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Колени внутрь (вальгус)',
        consequence: 'Стресс на коленные суставы',
        correction: 'Разводи колени по направлению носков',
      },
      {
        description: 'Пятки отрываются от пола',
        consequence: 'Нестабильность, нагрузка на колени',
        correction: 'Давли пятками в пол на протяжении всего движения',
      },
    ],
    setup_steps: [
      'Возьми гантель вертикально обеими руками у груди',
      'Ноги чуть шире плеч, носки на 15–30°',
      'Напряги кор, взгляд прямо',
    ],
    execution_steps: [
      'Отводи бёдра назад и вниз',
      'Колени двигаются наружу по линии носков',
      'Опустись до параллели или ниже',
      'Пауза 1 секунду внизу',
      'Встань, выталкивая пятки в пол',
    ],
    key_cues: ['Пятки в пол', 'Колени наружу', 'Грудь поднята'],
    safety_tips: ['Безопасное упражнение для большинства', 'При боли в колене — меньше глубину'],
    easier_variations: ['box_squat', 'squat_bodyweight'],
    harder_variations: ['front_squat', 'barbell_back_squat', 'paused_goblet_squat'],
    alternatives: ['leg_press', 'split_squat'],
    tags: ['compound', 'legs', 'beginner', 'home'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'dumbbell_row',
    name: 'Тяга гантели в наклоне',
    name_en: 'Dumbbell Row',
    category: 'back',
    movement_pattern: 'pull_horizontal',
    modality: 'strength',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps', 'rear_delts', 'traps'],
    equipment: ['dumbbell', 'bench'],
    location: ['home', 'gym'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [8, 12],
    default_rest_sec: 75,
    tempo: '1-1-3-0',
    breathing: 'Выдох при подъёме, вдох при опускании',
    contraindications: ['lower_back'],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Ротация корпуса при подъёме',
        consequence: 'Снижение эффективности, риск травмы',
        correction: 'Плечи параллельны полу — не крути корпус',
      },
    ],
    setup_steps: [
      'Колено и рука на скамье, корпус параллелен полу',
      'Другая нога стоит на полу для опоры',
      'Гантель в опущенной руке',
    ],
    execution_steps: [
      'Тяни локоть назад и вверх',
      'Гантель к бедру, не к плечу',
      'Медленно опускай — 3 секунды',
      'Полное растяжение широчайшей внизу',
    ],
    key_cues: ['Локоть назад', 'Плечи ровно', 'Медленно вниз'],
    safety_tips: ['Спина прямая, не округляй поясницу'],
    easier_variations: ['seated_cable_row', 'band_row'],
    harder_variations: ['barbell_bent_over_row', 'chest_supported_row'],
    alternatives: ['lat_pulldown', 'pull_up'],
    tags: ['compound', 'back', 'unilateral', 'beginner'],
    is_compound: true,
    is_bilateral: false,
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Жим гантелей сидя',
    name_en: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    movement_pattern: 'push_vertical',
    modality: 'strength',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps', 'traps'],
    equipment: ['dumbbell', 'bench'],
    location: ['home', 'gym'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [8, 12],
    default_rest_sec: 90,
    tempo: '2-0-1-0',
    breathing: 'Выдох на подъёме',
    contraindications: ['shoulder', 'neck'],
    risk_level: 'medium',
    common_mistakes: [
      {
        description: 'Прогиб поясницы',
        consequence: 'Нагрузка на поясничный отдел',
        correction: 'Сиди прямо, напряги пресс',
      },
    ],
    setup_steps: [
      'Сядь на скамью со спинкой, угол 90°',
      'Гантели на уровне плеч, локти под углом 90°',
      'Нейтральный хват или пронированный',
    ],
    execution_steps: [
      'Жми гантели вверх, сводя их над головой',
      'Не блокируй локти полностью вверху',
      'Медленно опускай на 2 секунды',
    ],
    key_cues: ['Спина ровная', 'Не касай гантелями вверху', 'Кор напряжён'],
    safety_tips: ['При проблемах с плечом — нейтральный хват', 'Не запрокидывай голову'],
    easier_variations: ['machine_shoulder_press', 'lateral_raise'],
    harder_variations: ['barbell_overhead_press', 'push_press', 'arnold_press'],
    alternatives: ['landmine_press', 'cable_shoulder_press'],
    tags: ['compound', 'shoulders', 'beginner'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'plank',
    name: 'Планка',
    name_en: 'Plank',
    category: 'core',
    movement_pattern: 'plank',
    modality: 'stability',
    primary_muscles: ['core', 'abs'],
    secondary_muscles: ['shoulders', 'glutes'],
    equipment: ['bodyweight', 'mat'],
    location: ['home', 'gym', 'outdoor'],
    difficulty: 1,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [30, 60],
    default_rest_sec: 45,
    tempo: 'изометрия',
    breathing: 'Ровное дыхание, не задерживай',
    contraindications: ['wrist'],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Провисание таза вниз',
        consequence: 'Нагрузка на поясницу',
        correction: 'Напряги ягодицы и пресс — таз ровно',
      },
    ],
    setup_steps: ['Упор на предплечьях или ладонях', 'Тело прямое', 'Взгляд в пол'],
    execution_steps: ['Удерживай позицию', 'Дыши ровно', 'Не задерживай дыхание'],
    key_cues: ['Тело прямое', 'Ягодицы напряжены', 'Не задерживай дыхание'],
    safety_tips: ['При боли в запястьях — на кулаках или предплечьях'],
    easier_variations: ['plank_on_knees', 'incline_plank'],
    harder_variations: ['plank_with_leg_raise', 'rk_plank', 'plank_to_pushup'],
    alternatives: ['dead_bug', 'hollow_body_hold'],
    tags: ['core', 'isometric', 'bodyweight', 'beginner'],
    is_compound: false,
    is_bilateral: true,
  },
  {
    id: 'dead_bug',
    name: 'Мёртвый жук',
    name_en: 'Dead Bug',
    category: 'core',
    movement_pattern: 'stability',
    modality: 'stability',
    primary_muscles: ['core', 'abs'],
    secondary_muscles: ['hip_flexors'],
    equipment: ['bodyweight', 'mat'],
    location: ['home', 'gym'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [8, 12] as [number, number],
    default_rest_sec: 45,
    tempo: 'медленно контролируемо',
    breathing: 'Выдох при опускании ноги',
    contraindications: ['lower_back'],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Поясница отрывается от пола',
        consequence: 'Отсутствует стабилизация кора',
        correction: 'Поясница прижата к полу на всём диапазоне',
      },
    ],
    setup_steps: ['Лечь на спину', 'Руки вертикально вверх', 'Ноги согнуты 90°'],
    execution_steps: [
      'Опускай противоположную руку и ногу',
      'Поясница прижата к полу',
      'Верни в исходное и смени сторону',
    ],
    key_cues: ['Поясница в пол', 'Медленно и контролируемо', 'Выдох при движении'],
    safety_tips: ['Безопасная замена скручиваниям при проблемах со спиной'],
    easier_variations: ['dead_bug_arms_only'],
    harder_variations: ['dead_bug_with_resistance_band'],
    alternatives: ['plank', 'hollow_body_hold'],
    tags: ['core', 'rehab_friendly', 'bodyweight'],
    is_compound: false,
    is_bilateral: false,
  },
  {
    id: 'romanian_deadlift',
    name: 'Румынская тяга',
    name_en: 'Romanian Deadlift',
    category: 'legs',
    movement_pattern: 'hinge',
    modality: 'strength',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['traps', 'core'],
    equipment: ['dumbbell', 'barbell'],
    location: ['gym', 'home'],
    difficulty: 3,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [8, 12],
    default_rest_sec: 90,
    tempo: '3-1-1-0',
    breathing: 'Вдох вниз, выдох при подъёме',
    contraindications: ['lower_back'],
    risk_level: 'medium',
    common_mistakes: [
      {
        description: 'Округление поясницы',
        consequence: 'Высокий риск травмы межпозвоночного диска',
        correction: 'Нейтральный позвоночник — прогиб в пояснице сохранён',
      },
    ],
    setup_steps: [
      'Ноги на ширине бёдер',
      'Гриф/гантели перед бёдрами',
      'Нейтральный позвоночник',
    ],
    execution_steps: [
      'Отводи таз назад, наклоняясь',
      'Гриф скользит по ногам вниз',
      'Опускайся до лёгкого натяжения задней поверхности',
      'Разгибай бёдра, возвращаясь вверх',
    ],
    key_cues: ['Таз назад', 'Спина прямая', 'Штанга у ног'],
    safety_tips: ['Никогда не округляй поясницу', 'Начинай с лёгкого веса'],
    easier_variations: ['good_morning_bodyweight', 'hip_hinge_band'],
    harder_variations: ['single_leg_rdl', 'barbell_rdl_heavy'],
    alternatives: ['leg_curl', 'glute_bridge'],
    tags: ['compound', 'hinge', 'hamstrings', 'intermediate'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'hip_thrust',
    name: 'Ягодичный мостик на скамье',
    name_en: 'Hip Thrust',
    category: 'glutes',
    movement_pattern: 'hinge',
    modality: 'strength',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['barbell', 'dumbbell', 'bench'],
    location: ['gym', 'home'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [10, 15],
    default_rest_sec: 75,
    tempo: '1-2-1-0',
    breathing: 'Выдох на подъёме',
    contraindications: [],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Гиперэкстензия поясницы наверху',
        consequence: 'Нагрузка на поясницу вместо ягодиц',
        correction: 'Таз параллелен полу наверху, не запрокидывай',
      },
    ],
    setup_steps: [
      'Лопатки на краю скамьи',
      'Ступни на полу, колени 90°',
      'Штанга на бёдрах с мягкой подкладкой',
    ],
    execution_steps: [
      'Опусти таз вниз',
      'Выталкивай таз вверх через пятки',
      'Пауза 2 секунды наверху — сожми ягодицы',
      'Медленно опускай',
    ],
    key_cues: ['Пауза наверху', 'Подбородок к груди', 'Пятки в пол'],
    safety_tips: ['Мягкая подкладка под штангу обязательна'],
    easier_variations: ['glute_bridge', 'glute_bridge_single_leg'],
    harder_variations: ['hip_thrust_single_leg', 'hip_thrust_paused'],
    alternatives: ['cable_pull_through', 'rdl'],
    tags: ['glutes', 'hip_hinge', 'beginner'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'lat_pulldown',
    name: 'Тяга верхнего блока',
    name_en: 'Lat Pulldown',
    category: 'back',
    movement_pattern: 'pull_vertical',
    modality: 'strength',
    primary_muscles: ['lats'],
    secondary_muscles: ['biceps', 'rear_delts'],
    equipment: ['cable'],
    location: ['gym'],
    difficulty: 2,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [8, 12],
    default_rest_sec: 75,
    tempo: '1-1-3-0',
    breathing: 'Выдох при тяге вниз',
    contraindications: ['neck', 'shoulder'],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Отклонение назад слишком сильно',
        consequence: 'Упражнение превращается в горизонтальную тягу',
        correction: 'Небольшой наклон назад (10–15°), не больше',
      },
    ],
    setup_steps: [
      'Сядь, зафиксируй бёдра под валики',
      'Широкий хват чуть шире плеч',
      'Небольшой прогиб в грудном отделе',
    ],
    execution_steps: [
      'Тяни гриф к верхней части груди',
      'Локти вниз и чуть назад',
      'Медленно разгибай руки — 3 секунды',
    ],
    key_cues: ['Локти вниз', 'Своди лопатки', 'Медленно вверх'],
    safety_tips: ['Тяни спереди, не за голову'],
    easier_variations: ['band_lat_pulldown', 'assisted_pullup'],
    harder_variations: ['pull_up', 'weighted_pullup'],
    alternatives: ['dumbbell_row', 'cable_row'],
    tags: ['compound', 'back', 'gym_only'],
    is_compound: true,
    is_bilateral: true,
  },
  {
    id: 'dumbbell_curl',
    name: 'Сгибания с гантелями',
    name_en: 'Dumbbell Bicep Curl',
    category: 'arms',
    movement_pattern: 'pull_vertical',
    modality: 'strength',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    equipment: ['dumbbell'],
    location: ['home', 'gym'],
    difficulty: 1,
    min_fitness_level: 'beginner',
    default_sets: [3, 4],
    default_reps: [10, 15],
    default_rest_sec: 60,
    tempo: '1-1-3-0',
    breathing: 'Выдох при сгибании',
    contraindications: [],
    risk_level: 'low',
    common_mistakes: [
      {
        description: 'Раскачка корпуса',
        consequence: 'Снятие нагрузки с бицепса',
        correction: 'Локти прижаты к туловищу, двигаются только предплечья',
      },
    ],
    setup_steps: ['Стой прямо, гантели по бокам', 'Ладони вперёд', 'Локти у корпуса'],
    execution_steps: [
      'Сгибай руки, не раскачиваясь',
      'Пауза 1 секунду наверху',
      'Медленно опускай — 3 секунды',
    ],
    key_cues: ['Локти у корпуса', 'Медленно вниз', 'Без раскачки'],
    safety_tips: ['Лёгкий вес с хорошей техникой эффективнее тяжёлого с читингом'],
    easier_variations: ['seated_dumbbell_curl'],
    harder_variations: ['hammer_curl', 'incline_curl', 'concentration_curl'],
    alternatives: ['barbell_curl', 'cable_curl'],
    tags: ['isolation', 'biceps', 'beginner'],
    is_compound: false,
    is_bilateral: false,
  },
]

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id)
}

export function getExercisesByCategory(category: string): Exercise[] {
  return EXERCISES.filter(e => e.category === category)
}

export function getExercisesForProfile(
  location: string,
  equipment: string[],
  restrictions: string[]
): Exercise[] {
  return EXERCISES.filter(ex => {
    if (!ex.location.includes(location as 'home' | 'gym' | 'outdoor')) return false
    const hasContraindication = ex.contraindications.some(c => restrictions.includes(c))
    if (hasContraindication) return false
    if (location === 'home' && equipment.length > 0) {
      const hasEquip = ex.equipment.some(e =>
        e === 'bodyweight' || e === 'mat' || equipment.includes(e)
      )
      if (!hasEquip) return false
    }
    return true
  })
}
